[package]
name = "mirage"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
serde = { version = "1.0.208", features = ["derive"] }
serde_yaml = "0.9.34"

[dev-dependencies]
tempdir = "0.3.7"
